config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root "events#index"
  resources :events

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :attendance

  validates :title, presence: true, length: { in: 5..140 }
  validates :start_date, presence: true 
  validate :future_event
  validates :duration, presence: true
  validates :description, presence: true, length: { in: 20..1000 }
  validates :location, presence: true
  validates :price, presence: true, length: { in: 1..1000 }

  private

  def future_event
    errors.add(:date, "Can't be in the past!") if date < Date.today
  end
  def event_send
    EventMailer.event_email(self).deliver_now
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :event
  has_many :attendances, through: :events

  
  after_create :welcome_send
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    # Méthode qui crée un event vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
    @event = Event.new
  end

  def create
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
    u = User.first
    @event = Event.new(title: params[:title], 
    start_date: params[:start_date],
    duration: params[:duration],
    description: params[:description],
    location: params[:location],
    price: params[:price] )
    @event.user = u
    if @event.save # essaie de sauvegarder en base @gossip
      # si ça marche, il redirige vers la page d'index du site
      flash[:success] = "Tu as ajouter ton super potin."
      redirect_to "/gossips"
    else
      # sinon, il render la view new (qui est celle sur laquelle on est déjà)
      flash.now[:error]
      render action: "new"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
	def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
  
    @user = User.new(first_name: params[:first_name], 
    last_name: params[:last_name], age: params[:age],
    email: params[:email], description: params[:description],
    password: params[:password])
   
    if @user.save 
      flash[:success] = "Bienvenue sur notre site."
      redirect_to "/"
    else
      flash.now[:error]
      render action: "new"
    end
  end
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/events/new.html.erb
<html>
  <body>
    <div class="container">
      <h1> Créer ton événement </h1>
      <%= form_tag url_for(action: 'create'), method: "post" do %>
      <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >
      <br />
      <%= label_tag "Titre de l'événement" %>
      <%= text_field_tag 'title', @event.title %>
      <%= label_tag "Date de début" %>
      <%= text_field_tag 'start_date', @event.start_date %>
      <%= label_tag "Durée" %>
      <%= text_field_tag 'duration', @event.duration %>
      <br /> <br />

      <%= label_tag "Description" %>
      <%= text_area_tag 'description', @event.description %>
      <br /> <br />

      <%= label_tag "Localisation" %>
      <%= text_field_tag 'location', @event.location %>
      <%= label_tag "Prix" %>
      <%= text_field_tag 'price', @event.price %>
      <br /> <br />
      
      <%= submit_tag "Créer cette événement" %>

      <% end %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event Share</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>
  
  <header>
    <nav class="navbar navbar-expand-lg navbar-light text-light bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <a class="navbar-brand text-white" <%= link_to "Event Share", root_path%></a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <a class="nav-link text-light" <%= link_to "Créer un Événement", new_event_path%></a>
          </li>
          <% if !(current_user) %>
            <li class="nav-item">
              <a class="nav-link text-light" <%= link_to "Se connecter", new_user_session_path%></a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" <%= link_to "S'inscrire", new_user_registration_path%></a>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link text-light" <%= link_to "Se deconnecter", destroy_user_session_path, method: :delete %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" <%= link_to "Mon profil", users_show_path%></a>
            </li>
          <% end %>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Profil
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "SignUp", new_user_registration_path, class: "dropdown-item" %>
              <%= link_to "SignIn", new_user_session_path, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
              <%= link_to "Profile", new_user_registration_path, class: "dropdown-item" %>
              <%= link_to "SignOut", destroy_user_session_path, class: "dropdown-item" %>
            </div>
          </li>
  
        </ul>
      </div>
    </nav>
  </header>

  
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<br><br><h1>Bienvenue sur ta page <%= @user.first_name%></h1><br><br><hr></hr>
<p>Ton prénom: <%= @user.first_name%></p>
<p>Ton nom: <%= @user.last_name%></p>
<p>Ton email : <%= @user.email%></p>
<li class="nav-item"> <%= link_to "Modifie ton profil", edit_user_registration_path,   class:"nav-link" %> </li>
<li class="nav-item"> <%= link_to "Complète ton profil", edit_user_path,   class:"nav-link" %> </li>
<hr></hr>

<h2>Tes événements</h2>